# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='rcmsg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\x05rcmsg\":\n\nCalRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x64\x61rts\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\")\n\x08\x43\x61lReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32@\n\nCalculator\x12\x32\n\nMonteCarlo\x12\x11.rcmsg.CalRequest\x1a\x0f.rcmsg.CalReply\"\x00\x62\x06proto3')
)




_CALREQUEST = _descriptor.Descriptor(
  name='CalRequest',
  full_name='rcmsg.CalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rcmsg.CalRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='darts', full_name='rcmsg.CalRequest.darts', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rcmsg.CalRequest.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=82,
)


_CALREPLY = _descriptor.Descriptor(
  name='CalReply',
  full_name='rcmsg.CalReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rcmsg.CalReply.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rcmsg.CalReply.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['CalRequest'] = _CALREQUEST
DESCRIPTOR.message_types_by_name['CalReply'] = _CALREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalRequest = _reflection.GeneratedProtocolMessageType('CalRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALREQUEST,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:rcmsg.CalRequest)
  ))
_sym_db.RegisterMessage(CalRequest)

CalReply = _reflection.GeneratedProtocolMessageType('CalReply', (_message.Message,), dict(
  DESCRIPTOR = _CALREPLY,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:rcmsg.CalReply)
  ))
_sym_db.RegisterMessage(CalReply)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='rcmsg.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=127,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='MonteCarlo',
    full_name='rcmsg.Calculator.MonteCarlo',
    index=0,
    containing_service=None,
    input_type=_CALREQUEST,
    output_type=_CALREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
